security:
  oauth2:
    client:
      clientId: 360796309369-f6joecbv8vubmkfh8l1248lrb3gdvrcq.apps.googleusercontent.com
      clientSecret: l3X6X3A8uhOEOVDqppimVi52
      accessTokenUri: https://www.googleapis.com/oauth2/v4/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
      clientAuthenticationScheme: form
      scope:
        - openid
        - email
        - profile
    resource:
      userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
      preferTokenInfo: true
# Server configuration
server:
  port: 8081